yachtcharter/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^$', CharterCatalogueView.as_view(), name = 'main'),
    url(r'^(?P<yacht_type_slug>[\w-]+)-catalog/$', CatalogueYachtListView.as_view(), name='catalogue_yacht_list'),
    url(r'^(?P<yacht_type_slug>[\w-]+)-catalog/(?P<yacht_slug>[\w-]+)/$', YachtDetailView.as_view(), name='yacht_detail'),
    url(r'^(?P<country_slug>[\w-]+)/(?P<yacht_type_slug>[\w-]+)/$', CharterYachtListView.as_view(), name='charter_yacht_list'),
    ]

yachtcharter/models.py
import os

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation

from utils import img_utils


class Region(models.Model):
    title = models.CharField(max_length=255)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order_id',)


class Country(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    sub_title = models.CharField(max_length=255, null=True)
    banner_image = models.ImageField(upload_to='yachtcharter/country/banner_image/')
    card_image = models.ImageField(upload_to='yachtcharter/country/card_image/', help_text='Auto resize to 736px')
    region = models.ForeignKey(Region)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.card_image.path):
            self.card_image = img_utils.resize_ratio(736, self.card_image.file)
        super(Country, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order_id',)


class YachtType(models.Model):
    # Set of classes names which used in ContentType
    SAILINGYACHT = 'sailingyacht'
    CATAMARAN = 'catamaran'
    MOTORYACHT = 'motoryacht'
    GULET = 'gulet'
    LUXYACHT = 'luxyacht'

    YACHT_TYPE = (
        (SAILINGYACHT, 'Sailing yachts'),
        (CATAMARAN, 'Catamarans'),
        (MOTORYACHT, 'Motor yachts'),
        (GULET, 'Gulets'),
        (LUXYACHT, 'Lux yachts')
    )
    yacht_type = models.CharField(max_length=255, choices=YACHT_TYPE, unique=True)

    title = models.CharField(max_length=255)
    slug = models.SlugField()
    title_nominative = models.CharField(max_length=255)
    title_genitive = models.CharField(max_length=255, null=True)
    title_prepositional = models.CharField(max_length=255, null=True)
    title_charter = models.CharField(max_length=255, null=True, help_text='Something like "Sailing yacht charter"')

    banner_image = models.ImageField(upload_to='yachtcharter/yachttype/banner_image/')
    card_image = models.ImageField(upload_to='yachtcharter/yachttype/card_image/', help_text='Auto resize to 740px')
    media_image = models.ImageField(upload_to='yachtcharter/yachttype/country_charter_media_image/')

    order_id = models.PositiveIntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.card_image.path):
            img = self.card_image.file
            self.card_image = img_utils.resize_ratio(740, img)
            self.media_image = img_utils.resize_ratio(120, img)
        super(YachtType, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('yachtcharter:catalogue_yacht_list', args=[self.slug])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order_id',)


class CountryCharter(models.Model):
    country = models.ForeignKey(Country,  verbose_name='Title')
    yacht_type = models.ForeignKey(YachtType)
    text_top = models.TextField(null=True, blank=True)
    text_bottom = models.TextField(null=True, blank=True)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.yacht_type.title_charter + ' | ' + self.country.title

    def get_absolute_url(self):
        return reverse('yachtcharter:charter_yacht_list', args=[self.country.slug, self.yacht_type.slug])

    class Meta:
        unique_together = (('country', 'yacht_type'))
        ordering = ('order_id',)


class ShipYard(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)


class YachtEntertainment(models.Model):
    title = models.CharField(max_length=255)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order_id',)


class YachtComfortPack(models.Model):
    title = models.CharField(max_length=255)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order_id',)


class Yacht(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    card_image = models.ImageField(upload_to='yachtcharter/yacht/', help_text = 'Auto resize to 740px')
    built_year = models.CharField(max_length=255, null=True, blank=True, help_text='Years of when model was produced')
    yacht_type = models.ForeignKey(YachtType)
    length = models.DecimalField(max_digits=5, decimal_places=2)
    beam = models.DecimalField(max_digits=4, decimal_places=2)
    cabin = models.CommaSeparatedIntegerField(max_length=255)
    bed = models.CharField(max_length=255)
    wc = models.CommaSeparatedIntegerField(max_length=255)
    brochure = models.FileField(upload_to='yachtcharter/brochure/', null=True, blank=True)
    photo_gallery = GenericRelation('photobank.YachtPhotoGallery')

    @staticmethod
    def get_class_by_type(yacht_type):
        return ContentType.objects.get(app_label="yachtcharter", model=yacht_type).model_class()

    def get_obj_by_type(self):
        return ContentType.objects.get(app_label="yachtcharter", model=self.yacht_type.yacht_type).get_object_for_this_type(yacht_ptr_id = self.id)

    def __str__(self):
        res = self.title + ' | ' + self.cabin + ' cabins'
        if self.built_year:
            res += ' | ' + self.built_year + ' year'
        return  res

    def _comma_separated_display(self, value):
        return value.replace(',', ' / ')

    @property
    def cabin_display(self):
        return self._comma_separated_display(self.cabin)

    @property
    def wc_display(self):
        return self._comma_separated_display(self.wc)

    def _to_ft(self, meter):
        return round((float(meter) * 3.28), 2)

    @property
    def length_ft(self):
        return self._to_ft(self.length)

    @property
    def beam_ft(self):
        return self._to_ft(self.beam)

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.card_image.path):
            self.card_image = img_utils.resize_ratio(740, self.card_image.file)
        super(Yacht, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('yachtcharter:yacht_detail', args=[self.yacht_type.slug, self.slug])

    class Meta:
        ordering = ('length', 'title')


class BareboatYacht(Yacht):
    engine_power = models.CharField(max_length=255)
    fuel_tank = models.CharField(max_length=255)
    water_tank = models.CharField(max_length=255)
    shipyard = models.ForeignKey(ShipYard)
    draft = models.DecimalField(max_digits=5, decimal_places=2)

    def draft_ft(self):
        return self._to_ft(self.draft)

    class Meta:
        abstract = True


class SailingYacht(BareboatYacht):
    def save(self, *args, **kwargs):
        self.yacht_type = YachtType.objects.get(yacht_type=YachtType.SAILINGYACHT)
        super(SailingYacht, self).save(*args, **kwargs)

    class Meta:
        ordering = ('length', 'title')


class Catamaran(BareboatYacht):
    entertainment = models.ManyToManyField(YachtEntertainment, blank=True)
    comfort_pack = models.ManyToManyField(YachtComfortPack, blank=True)
    def save(self, *args, **kwargs):
        self.yacht_type = YachtType.objects.get(yacht_type=YachtType.CATAMARAN)
        super(Catamaran, self).save(*args, **kwargs)

    class Meta:
        ordering = ('length', 'title')


class MotorYacht(BareboatYacht):
    max_speed = models.CharField(max_length=255)
    cruising_speed = models.CharField(max_length=255)
    fuel_consumption = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        self.yacht_type = YachtType.objects.get(yacht_type=YachtType.MOTORYACHT)
        super(MotorYacht, self).save(*args, **kwargs)

    class Meta:
        ordering = ('length', 'title')


class CrewedYacht(Yacht):
    crew_num = models.CharField(max_length=255)
    crew_info = models.TextField()
    cabin_info = models.TextField()
    entertainment = models.ManyToManyField(YachtEntertainment, blank=True)
    comfort_pack = models.ManyToManyField(YachtComfortPack, blank=True)

    class Meta:
        abstract = True


class GuletClass(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Gulet(CrewedYacht):
    gulet_class = models.ForeignKey(GuletClass)

    def save(self, *args, **kwargs):
        self.yacht_type = YachtType.objects.get(yacht_type=YachtType.GULET)
        super(Gulet, self).save(*args, **kwargs)

    class Meta:
        ordering = ('length', 'title')


class LuxYacht(CrewedYacht):
    shipyard = models.ForeignKey(ShipYard)
    engine_power = models.CharField(max_length=255)
    max_speed = models.CharField(max_length=255)
    cruising_speed = models.CharField(max_length=255)
    fuel_consumption = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
        self.yacht_type = YachtType.objects.get(yacht_type=YachtType.LUXYACHT)
        super(LuxYacht, self).save(*args, **kwargs)

    class Meta:
        ordering = ('length', 'title')


class YachtCharter(models.Model):
    country = models.ForeignKey(Country)
    yacht = models.ForeignKey(Yacht)
    built_year = models.CharField(max_length=255, null=True)
    cabin = models.CharField(max_length=255)
    wc = models.CharField(max_length=255)
    start_port = models.CharField(max_length=255, null=True)

    def crewed_charter_price_from(self):
        return YachtCharter.objects.annotate(value=models.Min('yachtcharterpricelist__yachtchartercrewedpriceline__week_price')).get(id=self.id)

yachtcharter/templates/yachtcharter/catalogue_yacht_list.html
{% extends "base.html" %}
{% load banner %}
{% load seo %}

{% block meta-data %}{% meta_data request.path yacht_list.number %}{% endblock %}

{% block pagination %}
    {% if yacht_list.has_previous %}
        <link rel="prev" href="{% path_to_page yacht_list.previous_page_number %}">
    {% endif %}
    {% if yacht_list.has_next %}
        <link rel="next" href="{% autoescape on %}{% path_to_page yacht_list.next_page_number %}{% endautoescape %}">
    {% endif %}
{% endblock %}

{% block banner-image %}{{ yacht_type.banner_image.url }}{% endblock %}
{% block banner-breadcrumbs %}{% breadcrumbs_show 'yachtcharter:main' yacht_type.get_absolute_url yacht_type.title %}{% endblock %}
{% block banner-title %}{{ yacht_type.title }}{% endblock %}
{% block banner-subtitle %}{{ yacht_type.title_charter }}{% endblock %}
{% block banner-filter %}
            <div class="section dark-translucent-bg">
            <div class="container">
                <div class="sorting-filters text-center mb-20">
                    {% csrf_token %}
                    <form class="form-inline" action="{{ yacht_type.get_absolute_url }}" method="get">
                        {% if filter_list.country %}
                            <div class="form-group ph-20">
                                <label>Страна&nbsp;аренды</label>
                                <select class="form-control yacht-filter" name="country">
                                    <option selected value="all" class="option-title">Все</option>
                                    {% for filter in filter_list.country %}
                                        <option {% if active_filter.country == filter.country__slug %} selected {% endif %}
                                                                                                       value="{{ filter.country__slug }}">{{ filter.country__title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                        {% if filter_list.shipyard %}
                            <div class="form-group ph-20">
                                <label>Бренд</label>
                                <select class="form-control" name="shipyard">
                                    <option selected value="all" class="option-title">Все</option>
                                    {% for filter in filter_list.shipyard %}
                                        <option {% if active_filter.shipyard == filter.shipyard__slug %} selected {% endif %}
                                            value="{{ filter.shipyard__slug }}">{{ filter.shipyard__title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                        <div class="form-group ph-20">
                            <label>Кают</label>
                            <select class="form-control yacht-filter" name="cabin">
                                <option value="all" class="option-title">Все</option>
                                {% for filter in filter_list.cabin %}
                                    <option {% if active_filter.cabin == filter %} selected {% endif %} value="{{ filter }}">
                                        {{ filter }} кают{% if filter == 1 %}а{% elif filter < 5 %}ы{% endif %}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group ph-20">
                            <button class="btn btn-default btn-animated" type="submit">Найти <i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}


{% block main-container %}
    <div class="main-container">
        <div class="container">
            <div class="row">
                <div class="main col-md-12">
                    <div class="row">
                    {% for yacht in yacht_list %}
                        <div class="col-md-4 col-sm-6">
                            <div class="listing-item white-bg bordered mb-20">
                                <div class="overlay-container">
                                    <img src="{{ yacht.card_image.url }}" alt="{{ yacht.title }}">
                                    <a href="{{ yacht.get_absolute_url }}" class="overlay-link"><i class="fa fa-anchor"></i> </a>
                                    {% if yacht.gulet or yacht.luxyacht %}
                                        {% load humanize %}
                                        <span class="badge">
                                        {% for yachtcharter in yacht.yachtcharter_set.all %}
                                            {{ yachtcharter.country.title }} от {{ yachtcharter.crewed_charter_price_from.value|intcomma }} € / неделя<br>
                                        {% endfor %}
                                        </span>
                                    {% endif %}
                                </div>
                                <div class="body">
                                    <h3><a href="{{ yacht.get_absolute_url }}">{{ yacht.title }}</a></h3>
                                    <div class="separator-2"></div>
                                    <ul class="list-unstyled">
                                        {% if yacht.sailingyacht or yacht.catamaran or yacht.motoryacht or yacht.luxyacht %}
                                            <li><span class="pr-5">Бренд:</span> {{ yacht.shipyard.title }}</li>
                                        {% endif %}
                                        <li><span class="pr-5">Длина:</span> {{ yacht.length }} м = {{ yacht.length_ft }} фт</li>
                                        <li>
                                            <ul class="list-inline margin-clear">
                                                <li>Кают: {{ yacht.cabin_display }}</li>
                                                <li>WC: {{ yacht.wc_display }}</li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <p class="lead text-center">К сожалению, по Вашему запросу ничего не найдено.</p>
                    {% endfor %}
                    </div>
                    {% if yacht_list.has_other_pages %}
                        <div class="clearfix"></div>
                        <nav>
                            <ul class="pagination">
                                {% if yacht_list.has_previous %}
                                    <li><a href="{% path_to_page yacht_list.previous_page_number %}" aria-label="Previous"><i class="fa fa-angle-left"></i></a></li>
						        {% endif %}
                                {% for page_num in yacht_list.paginator.page_range  %}
                                    {% if page_num == yacht_list.number %}
                                        <li class="active"><a href="#">{{ page_num }}<span class="sr-only">(current)</span></a></li>
                                    {% else %}
                                        <li><a href="{% path_to_page page_num %}">{{ page_num }}</a></li>
                                    {% endif %}
						        {% endfor %}
                                {% if yacht_list.has_next %}
                                    <li><a href="{% path_to_page yacht_list.next_page_number %}" aria-label="Previous"><i class="fa fa-angle-right"></i></a></li>
						        {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

yachtcharter/templates/yachtcharter/charter_catalogue.html
{% extends "base.html" %}
{% load staticfiles %}
{% load banner %}


{% block banner-image %}{% menu_banner_image 'yachtcharter:main' %}{% endblock %}
{% block banner-breadcrumbs %}{% breadcrumbs_show 'yachtcharter:main' %}{% endblock %}
{% block banner-title %}{% menu_banner_title 'yachtcharter:main' %}{% endblock %}
{% block banner-subtitle %}{% menu_banner_subtitle 'yachtcharter:main' %}{% endblock %}


{% block main-container %}
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="main col-md-12">
                {% for region in charterregion_list %}
                    <h2 class="text-center">{{ region.title }}</h2>
                    <div class="separator"></div>
                    <br>
                    <div class="row">
                        {% for country in region.country_set.all %}
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                                <div class="image-box shadow text-center mb-20  style-2">
                                    <div class="overlay-container offer-card">
                                        <img src="{{ country.card_image.url }}" alt="{{ country.title }}">
                                        <div class="overlay-top">
                                            <div class="text">
                                                <h3>Аренда яхт</h3>
                                            </div>
                                        </div>
                                        <div class="overlay-bottom">
                                            <div class="links">
                                                {% for charter in country.countrycharter_set.all %}
                                                    <a href="{{ charter.get_absolute_url }}" class="btn btn-gray-transparent btn-animated btn-sm">{{ charter.yacht_type.title }}<i class="pl-10 fa fa-arrow-right"></i></a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="body">
                                        <h4>{{ country.title }}</h4>
                                        <div class="separator"></div>
                                        <p>{{ country.sub_title }}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <br>
                {% endfor %}
                <h2 class="text-center">Выбрать яхту из каталога</h2>
                <div class="separator"></div>
                <br>
                <div class="row">
                    {% for yacht_type in yachttype_list %}
                        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12" >
                            <div class="image-box shadow text-center mb-20  style-2">
                                <div class="overlay-container offer-card">
                                    <img src="{{ yacht_type.card_image.url }}" alt="{{ yacht_type.title }}">
                                    <a href="{{ yacht_type.get_absolute_url }}" class="overlay-link"><i class="fa fa-anchor"></i> </a>
                                </div>
                                <div class="body">
                                    <h4>{{ yacht_type.title }}</h4>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}