countryhandbook/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^$', CountryList.as_view(), name = 'main'),
    url(r'^(?P<slug>[\w-]+)/$', CountryDetail.as_view(), name='country_detail'),
    ]

countryhandbook/models.py
import os

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.fields import GenericRelation

from utils import img_utils



class Region(models.Model):
    title = models.CharField(max_length=255)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order_id',)


class Country(models.Model):
    region = models.ForeignKey(Region)
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    subtitle = models.CharField(max_length=255, null=True)
    banner_image = models.ImageField(upload_to='countryhandbook/country/banner_image/')
    card_image = models.ImageField(upload_to='countryhandbook/country/card_image/', help_text='Auto resize to 740px')
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.card_image.path):
            self.card_image = img_utils.resize_ratio(740, self.card_image.file)
        super(Country, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('countryhandbook:country_detail', args=[self.slug])

    class Meta:
        ordering = ('order_id',)


class CountrySection(models.Model):
    country = models.OneToOneField(Country)
    title = models.CharField(max_length=255)
    menu_title = models.CharField(max_length=255)
    menu_slug = models.SlugField()

    def __str__(self):
        return self.title + ' | ' + self.country.title

    class Meta:
        abstract = True


class Charter(CountrySection):
    pass


class CharterEntry(models.Model):
    charter = models.ForeignKey(Charter)
    country_charter = models.OneToOneField('yachtcharter.CountryCharter')
    media_heading = models.CharField(max_length=255)
    media_body = models.TextField()
    order_id = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        ordering = ('order_id',)


class Yachting(CountrySection):
    entry_text = models.TextField()


class Info(CountrySection):
    pass


class InfoEntry(models.Model):
    info = models.ForeignKey(Info)
    title = models.CharField(max_length=255)
    entry_text = models.TextField()
    order_id = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        ordering = ('order_id',)


class Marina(CountrySection):
    pass


class MarinaEntry(models.Model):
    marina = models.ForeignKey(Marina)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='countryhandbook/marina/', help_text='Auto resize to 850px')
    map_link = models.URLField(max_length=255)
    plan = models.FileField(upload_to='countryhandbook/marina/plans/', null=True, blank=True)
    location = models.TextField()
    contacts = models.TextField()
    entry_text = models.TextField()
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.image.path):
            self.image = img_utils.resize_ratio(850, self.image.file)
        super(MarinaEntry, self).save(*args, **kwargs)

    class Meta:
        ordering = ('order_id',)


class Route(CountrySection):
    pass


class RouteEntry(models.Model):
    route = models.ForeignKey(Route)
    title = models.CharField(max_length=255)
    start_port = models.CharField(max_length=255)
    length = models.PositiveIntegerField()
    map = models.ImageField(upload_to='countryhandbook/route/', help_text='Auto resize to 850px')
    map_url = models.URLField(blank=True, null=True)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.title + ' | ' + self.route.country.title

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.map.path):
            self.map = img_utils.resize_ratio(850, self.map.file)
        super(RouteEntry, self).save(*args, **kwargs)

    class Meta:
        ordering = ('order_id',)


class RouteEntryDay(models.Model):
    entry = models.ForeignKey(RouteEntry)
    checkpoint = models.TextField()
    length = models.PositiveIntegerField(blank=True, null=True)
    order_id = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        ordering = ('order_id',)


class Showplace(CountrySection):
    pass


class ShowplaceEntry(models.Model):
    showplace = models.ForeignKey(Showplace)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='countryhandbook/showplace/', help_text='Auto resize to 850px')
    address = models.TextField()
    opening_hours = models.TextField(null=True, blank=True)
    ticket_price = models.TextField(null=True, blank=True)
    recommend = models.TextField(null=True, blank=True)
    entry_text = models.TextField()
    order_id = models.PositiveIntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.image.path):
            self.image = img_utils.resize_ratio(850, self.image.file)
        super(ShowplaceEntry, self).save(*args, **kwargs)

    class Meta:
        ordering = ('order_id',)

countryhandbook/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Country, Region


class CountryList(ListView):
    queryset = Region.objects.prefetch_related('country_set').all()
    context_object_name = 'region_list'
    template_name = 'countryhandbook/country_list.html'


class CountryDetail(DetailView):
    queryset = Country.objects.prefetch_related('charter__charterentry_set__country_charter__yacht_type').all()
    context_object_name = 'country'
    template_name = 'countryhandbook/country_detail.html'

countryhandbook/templates/countryhandbook/country_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load banner %}
{% load seo %}

{% block meta-og %}
    <meta property="og:type" content="article" />
    <meta property="og:site_name" content="{% site_name %}" >
    <meta property="fb:app_id" content="{% fb_id %}" />
    <meta property="og:title" content="{{ country.title  }} - {{ country.subtitle }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="http://{{ request.get_host }}{{ country.card_image.url }}" />
{% endblock %}


{% block banner-image %}{{ country.banner_image.url }}{% endblock %}
{% block banner-breadcrumbs %}{% breadcrumbs_show 'countryhandbook:main' country.get_absolute_url country.title %}{% endblock %}
{% block banner-title %}{{ country.title }}{% endblock %}
{% block banner-subtitle %}{{ country.subtitle }}{% endblock %}


{% block main-container %}
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="main col-md-9">
                    <div id="{{ country.charter.menu_slug }}" class="blogpost">
                        <h2 class="space-top">{{ country.charter.title }}</h2>
                        <div class="separator-2"></div>
                        {% for charter in country.charter.charterentry_set.all %}
                            <div class="media">
                                <div class="media-left">
                                    <div class="overlay-container">
                                        <img class="media-object" src="{{ charter.country_charter.yacht_type.media_image.url }}" alt="{{ charter.title }}">
                                        <a href="{{ charter.country_charter.get_absolute_url }}" class="overlay-link small"><i class="fa fa-anchor"></i></a>
                                    </div>
                                </div>
                                <div class="media-body">
                                    <h3 class="media-heading"><a href="{{ charter.country_charter.get_absolute_url }}">{{ charter.media_heading }}</a></h3>
                                    {{ charter.media_body|safe }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div id="{{ country.yachting.menu_slug }}" class="blogpost">
                        <h2 class="space-top">{{ country.yachting.title }}</h2>
                        <div class="separator-2"></div>
                        {{ country.yachting.entry_text|safe }}
                    </div>
                    <div id="{{ country.route.menu_slug }}" class="blogpost">
                        <h2 class="space-top">{{ country.route.title }}</h2>
                        <div class="separator-2"></div>
                        {% for route in country.route.routeentry_set.all %}
                            <h3>Маршрут № {{ route.order_id }} — {{ route.title }}</h3>
                            <div class="alert alert-info">
                                <p>Порт старта: <strong>{{ route.start_port }}</strong>. Общая протяженность маршрута: <strong>{{ route.length }} миль</strong></p>
                            </div>
                            <div class="table-responsive">
                            <table class="table table-striped">
                                <tbody>
                                {% for day in route.routeentryday_set.all %}
                                    <tr>
                                        <td>День&nbsp;{{ day.order_id }}</td>
                                        <td>{{ day.checkpoint|safe }}</td>
                                        <td>{% if day.length %}{{ day.length }}&nbsp;миль{% else %}—{% endif %}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            </div>
                            <img src="{{ route.map.url }}" class="img-responsive" alt="Яхтенный маршрут {{ route.title }}">
                            {% if route.map_url %}
                                <p class="mt-10"><a href="{{ route.map_url }}" rel="nofollow" target="_blank">Посмотреть маршрут на карте</a></p>
                            {% endif %}
                            {% if not forloop.last %}
                                <div class="space-bottom"></div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div id="{{ country.marina.menu_slug }}" class="blogpost">
                        <h2 class="space-top">{{ country.marina.title }}</h2>
                        <div class="separator-2"></div>
                        {% for marina in country.marina.marinaentry_set.all %}
                            <img class="img-responsive mb-20" src="{{ marina.image.url }}" alt="Марина {{ marina.title }}">
                            <h3>{{ marina.title }}</h3>
                            {{ marina.entry_text|safe }}
                            <div class="clearfix"></div>
                            <div class="well well-sm">
                                <div class="row">
                                    <div class="col-md-6 col-sm-6 col-xs-12 ">
                                        <h4>Адрес</h4>
                                        {{ marina.location|safe }}
                                        {% if marina.plan %}
                                            <a href="{{ marina.plan.url }}">Скачать план марины</a><br>
                                        {% endif %}
                                        <a href="{{ marina.map_link }}" target="_blank" rel="nofollow">Посмотреть расположение на карте</a>
                                    </div>
                                    <div class="col-md-6 col-sm-6 col-xs-12 ">
                                        <h4>Контакты</h4>
                                        {{ marina.contacts|safe }}
                                    </div>
                                </div>
                            </div>
                            {% if not forloop.last %}
                                <div class="space-bottom"></div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div id="{{ country.showplace.menu_slug }}" class="blogpost">
                        <h2 class="space-top">{{ country.showplace.title }}</h2>
                        <div class="separator-2"></div>
                        {% for showplace in country.showplace.showplaceentry_set.all %}
                            <img class="img-responsive mb-20" src="{{ showplace.image.url }}" alt="{{ showplace.title }}">
                            <h3>{{ showplace.title }}</h3>
                            {{ showplace.entry_text|safe }}
                            <div class="clearfix"></div>
                                <div class="well well-sm">
                                    <h4>Адрес</h4>
                                    {{ showplace.address|safe }}
                                </div>
                                {% if showplace.opening_hours %}
                                    <div class="well well-sm">
                                        <h4>Время работы</h4>
                                        {{ showplace.opening_hours|safe }}
                                    </div>
                                {% endif %}
                                {% if showplace.ticket_price %}
                                    <div class="well well-sm">
                                        <h4>Стоимость билета</h4>
                                        {{ showplace.ticket_price|safe }}
                                    </div>
                                {% endif %}
                                {% if showplace.recommend %}
                                    <div class="well well-sm">
                                        <h4>Рекомендации</h4>
                                        {{ showplace.recommend|safe }}
                                    </div>
                                {% endif %}
                            {% if not forloop.last %}
                                <div class="space-bottom"></div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div id="{{ country.info.menu_slug }}" class="blogpost">
                        <h2 class="space-top">{{ country.info.title }}</h2>
                        <div class="separator-2"></div>
                        {% for info in country.info.infoentry_set.all %}
                            <h3 >{{ info.title }}</h3>
                            {{ info.entry_text|safe }}
                            {% if not forloop.last %}
                                <div class="space-bottom"></div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="blogpost full">
                        <footer class="clearfix">
                            <div class="link pull-left">
                                {% include "socialshare.html" %}
                            </div>
                        </footer>
                    </div>
                </div>
                <aside class="col-md-3 hidden-xs hidden-sm">
                    <div class="sidebar">
                        <nav class="affix-menu scrollspy">
                            <ul class="smooth-scroll nav nav-pills nav-stacked">
                                <li><a href="#{{ country.charter.menu_slug }}">{{ country.charter.menu_title }}</a></li>
                                <li><a href="#{{ country.yachting.menu_slug }}">{{ country.yachting.menu_title }}</a></li>
                                <li><a href="#{{ country.route.menu_slug }}">{{ country.route.menu_title }}</a></li>
                                <li><a href="#{{ country.marina.menu_slug }}">{{ country.marina.menu_title }}</a></li>
                                <li><a href="#{{ country.showplace.menu_slug }}">{{ country.showplace.menu_title }}</a></li>
                                <li><a href="#{{ country.info.menu_slug }}">{{ country.info.menu_title }}</a></li>
                            </ul>
                        </nav>
                    </div>
                </aside>
            </div>
        </div>
    </section>
{% endblock %}

countryhandbook/templates/countryhandbook/country_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load banner %}


{% block banner-image %}{% menu_banner_image 'countryhandbook:main' %}{% endblock %}
{% block banner-breadcrumbs %}{% breadcrumbs_show 'countryhandbook:main' %}{% endblock %}
{% block banner-title %}{% menu_banner_title 'countryhandbook:main' %}{% endblock %}
{% block banner-subtitle %}{% menu_banner_subtitle 'countryhandbook:main' %}{% endblock %}


{% block main-container %}
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="main col-md-12">
                {% for region in region_list %}
                    <h2 class="text-center">{{ region.title }}</h2>
                    <div class="separator"></div>
                    <br>
                    <div class="row">
                        {% for country in region.country_set.all %}
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12" >
                                <div class="image-box shadow text-center mb-20  style-2">
                                    <div class="overlay-container offer-card">
                                        <img src="{{ country.card_image.url }}" alt="{{ country.title }}">
                                        <a href="{{ country.get_absolute_url }}" class="overlay-link"><i class="fa fa-anchor"></i> </a>
                                    </div>
                                    <div class="body">
                                        <h4>{{ country.title }}</h4>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}