faq/urls.py
from django.conf.urls import url

from .views import *



urlpatterns = [
    url(r'^$', QuestionList.as_view(), name = 'main'),
    ]

feedbackform/urls.py
from django.conf.urls import url

from .views import *



urlpatterns = [
    url(r'^proschitat-tur-na-yahte/$', TourCalculationView.as_view(), name='tour_calculation'),
    url(r'^bareboat-yacht-charter/(?P<price_id>[0-9]+)/$', BareboatYachtCharterView.as_view(), name='bareboat_yacht_charter'),
    url(r'^crewed-yacht-charter/(?P<price_id>[0-9]+)/$', CrewedYachtCharterView.as_view(), name='crewed_yacht_charter'),
    url(r'^cabin-yacht-charter/(?P<price_id>[0-9]+)/$', CabinCharterView.as_view(), name='cabin_charter'),
    url(r'^school-theory/$', SchoolTheoryView.as_view(), name='school_theory'),
    url(r'^school-cruise/(?P<price_id>[0-9]+)/$', SchoolCruiseView.as_view(), name='school_cruise'),
    url(r'^yacht-catalogue/(?P<yacht_id>[0-9]+)/$', YachtCatalogueView.as_view(), name='yacht_catalogue'),
    url(r'^contact-us/$', ContactUsView.as_view(), name='contact_us'),
    url(r'^faq/$', FaqView.as_view(), name='faq'),
    url(r'^thankyou/(?P<order_id>[0-9]+)/$', ThankYouView.as_view(), name='thankyou'),
    ]

sunsailing2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from django.contrib.flatpages.sitemaps import FlatPageSitemap

from sunsailing2.sitemap import *


sitemaps = {
    'yachtcharterstaticview': YachtCharterStaticSitemap,
    'yachts': YachtSitemap,
    'countrycharter': CountryCharterSitemap,
    'yachttype': YachtTypeSitemap,

    'cabincharterstatic': CabinCharterStaticSitemap,
    'cabinchartercurrentoffer': CabinCharterCurrentOfferSitemap,
    'cabincharterarchiveoffer': CabinCharterArchiveOfferSitemap,

    'schoolcruisestatic': SchoolCruiseListStaticSitemap,
    'schooltheory': SchoolTheorySitemap,
    'schoolcruise': SchoolCruiseSitemap,

    'countryhdbkstatic': CountryHdbkStaticSitemap,
    'countryhdbk': CountryHdbkSitemap,

    'faqstatic': FaqStaticSitemap,

    'flatpages': FlatPageSitemap
}


urlpatterns = [
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                  url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
                  url(r'^redactor/', include('redactor.urls')),


                  url(r'^blog/', include('blog.urls', namespace='blog')),
                  url(r'^kruizy-na-yahte/', include('cabincharter.urls', namespace='cabincharter')),
                  url(r'^shkola-yahtinga/', include('school.urls', namespace='school')),
                  url(r'^arenda-yaht/', include('yachtcharter.urls', namespace='yachtcharter')),
                  url(r'^strany-dlya-yahtinga/', include('countryhandbook.urls', namespace='countryhandbook')),
                  url(r'^voprosy-i-otvety/', include('faq.urls', namespace='faq')),
                  url(r'^otpravit-zayavku/', include('feedbackform.urls', namespace='feedbackform')),
                  url(r'^$', views.flatpage, {'url': '/'}, name='home'),
                  url(r'^kontakty/$', views.flatpage, {'url': '/kontakty/'}, name='contacts'),
                  url(r'^photobank/', include('photobank.urls', namespace='photobank')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load compress %}
{% load seo %}
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="{% block meta-robots %}follow,index{% endblock %}" name="robots">
        {% block meta-data %}{% meta_data request.path page_obj.number %}{% endblock %}
        {% block meta-og %}{% endblock %}
        {% block pagination %}{% endblock %}
        <link rel="icon" type="image/png" href="{% static 'base/images/favicon-16x16.png' %}" sizes="16x16">
        <link rel="icon" type="image/png" href="{% static 'base/images/favicon-32x32.png' %}" sizes="32x32">
        <link rel="icon" type="image/png" href="{% static 'base/images/favicon-96x96.png' %}" sizes="96x96">
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic&amp;subset=latin,cyrillic' rel='stylesheet' type='text/css'>
        {% compress css %}
            <link href="{% static 'bootstraptemplate/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'bootstraptemplate/fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
            <link href="{% static 'bootstraptemplate/fonts/fontello/css/fontello.css' %}" rel="stylesheet">
            <link href="{% static 'bootstraptemplate/css/animations.css' %}" rel="stylesheet">
            <link href="{% static 'bootstraptemplate/plugins/hover/hover-min.css' %}" rel="stylesheet">
            {% block extra-css %}{% endblock %}
            <link href="{% static 'bootstraptemplate/css/style.css' %}" rel="stylesheet" >
            <link href="{% static 'bootstraptemplate/css/skins/light_blue.css' %}" rel="stylesheet">
            <link href="{% static 'bootstraptemplate/css/custom.css' %}" rel="stylesheet">
        {% endcompress %}
	</head>
	<body>

		<div class="scrollToTop circle"><i class="icon-up-open-big"></i></div>
		<div class="page-wrapper">
            {% include 'navbar.html' %}
            {% block banner %}
                <div class="banner dark-translucent-bg" style="background-image:url('{% block banner-image %}{% endblock %}'); background-position: 50% 32%;">
                    {% block banner-breadcrumbs %}{% endblock %}
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 text-center col-md-offset-2 pv-20">
                                <h1 class="title object-non-visible" data-animation-effect="fadeIn" data-effect-delay="100">{% block banner-title %}{% endblock %}</h1>
                                <div class="separator object-non-visible mt-10" data-animation-effect="fadeIn" data-effect-delay="100"></div>
                                {% block banner-subtitle-wrapper %}<p class="large text-center object-non-visible" data-animation-effect="fadeIn" data-effect-delay="100">{% block banner-subtitle %}{% endblock %}</p>{% endblock %}
                            </div>
                        </div>
                    </div>
                    {% block banner-filter %}{% endblock %}
                </div>
            {% endblock %}
            {% block main-container %}{% endblock %}
            {% include "footer.html" %}
            <div id="fb-root"></div>
        </div>
        {% block js-api %}{% endblock %}
        {% compress js %}
            <script type="text/javascript" src="{% static 'bootstraptemplate/plugins/jquery.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstraptemplate/bootstrap/js/bootstrap.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstraptemplate/plugins/modernizr.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstraptemplate/plugins/waypoints/jquery.waypoints.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstraptemplate/plugins/jquery.validate.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstraptemplate/plugins/jquery.browser.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstraptemplate/plugins/SmoothScroll.js' %}"></script>
            <script type="text/javascript" src="{% static 'bootstraptemplate/js/template.js' %}"></script>
            <script type="text/javascript" src="{% static 'base/js/ajaxforms.js' %}"></script>
            <script type="text/javascript" src="{% static 'base/js/facebook.js' %}"></script>
		    {% block extra-js %}{% endblock %}
        {% endcompress %}
    </body>
</html>

templates/footer.html
{% load staticfiles %}
{% load form_tag %}
<footer id="footer" class="clearfix">
    <div class="footer">
        <div class="container">
            <div class="footer-inner">
                <div class="row">
                    <div class="col-md-4 col-sm-6">
                        <div class="footer-content">
                            <div class="logo-footer"><img id="logo-footer" src="{% static 'base/images/logo.png' %}" alt="sunSailing"></div>
                            <h6>Контакты</h6>
                            <address>
                                <ul class="list-inline mb-20">
                                    <li><i class="text-default fa fa-map-marker pl-10 pr-5"></i> ул. Ильинская 12, г. Киев, Украина</li>
                                </ul>
                                <ul class="list-inline mb-20">
                                    <li><i class="text-default fa fa-phone pl-10 pr-5"></i> +380 (44) 383-31-57</li>
                                    <li><i class="text-default fa fa-mobile pl-10 pr-5"></i> +380 (67) 226-83-96</li>
                                </ul>
                                <ul class="list-inline mb-20">
                                    <li><a href="mailto:office@sunsailing.com.ua"><i class="text-default fa fa-envelope-o pl-10 pr-5"></i> office@sunsailing.com.ua</a></li>
                                    <li><a href="skype:sunsailingua?add" title="Добавить sunsailingua в список контактов Skype"><i class="text-default fa fa-skype pr-5 pl-10"></i> sunsailingua</a></li>
                                </ul>
                            </address>
                            <h6>График работы</h6>
                            <ul class="list-unstyled mb-20">
                                <li><i class="pl-10"></i>Понедельник &mdash; Пятница: c 10:00 до 19:00</li>
                                <li><i class="pl-10"></i>Суббота: с 10:00 до 15:00</li>
                            </ul>
                            <h6>Для партнеров</h6>
                            <p class="pl-10">Приглашаем к сотрудничеству: туристические агентства, капитанов, свадебные агентства, ивент-агентства и др. <a href="/sotrudnichestvo/">Подробнее...</a></p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6">
                        <div class="footer-content">
                        <h2 class="title">Ставьте лайк</h2>
                        <div class="fb-page" data-href="https://www.facebook.com/sunSailing.com.ua" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/sunSailing.com.ua"><a href="https://www.facebook.com/sunSailing.com.ua">sunSailing</a></blockquote></div></div>
                        <div class="separator-2 mt-20"></div>
                            <ul class="social-links circle margin-clear animated-effect-1">
                                <li class="facebook"><a rel="nofollow" target="_blank" href="https://www.facebook.com/sunSailing.com.ua"><i class="fa fa-facebook"></i></a></li>
                                <li class="youtube"><a rel="nofollow" target="_blank" href="https://www.youtube.com/user/sunSailingYachts"><i class="fa fa-youtube"></i></a></li>
                                <li class="instagram"><a target="_blank" href="https://instagram.com/sunsailingua/"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="footer-content">
                            <h2 class="title">Напишите нам</h2>
                            {% contact_us_form as contact_us_form %}
                            <form id="contact_us" class="margin-clear" method="POST" action="{% url 'feedbackform:contact_us' %}">
                                {% csrf_token %}
                                <div class="form-group has-feedback {% if contact_us_form.name.errors %}has-error{% endif %}">
                                    <label class="sr-only" for="{{ contact_us_form.name.id_for_label }}"><strong>{{ contact_us_form.name.label }}</strong></label>
                                    {{ contact_us_form.name }}
                                    <i class="fa fa-user form-control-feedback"></i>
                                </div>
                                <div class="form-group has-feedback {% if contact_us_form.email.errors %}has-error{% endif %}">
                                    <label class="sr-only" for="{{ contact_us_form.email.id_for_label }}"><strong>{{ contact_us_form.email.label }}</strong></label>
                                    {{ contact_us_form.email }}
                                    <i class="fa fa-envelope form-control-feedback"></i>
                                </div>
                                <div class="form-group has-feedback {% if contact_us_form.message.errors %}has-error{% endif %}">
                                    <label class="sr-only" for="{{ contact_us_form.message.id_for_label }}">{{ contact_us_form.message.label }}</label>
                                    {{ contact_us_form.message }}
                                    <i class="fa fa-pencil form-control-feedback"></i>
                                </div>
                                <div class="alert hidden"></div>
                                <input value="Отправить" class="margin-clear submit-button btn btn-default" type="submit">
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="subfooter">
        <div class="container">
            <div class="subfooter-inner">
                <div class="row">
                    <div class="col-md-12">
                        <p class="text-center">© 2012 &mdash; {% now "Y"%} <a href="/">sunSailing</a>. Все права защищены.</p>
                        <p class="text-center"><a class="text-muted" href="/terms/"><small>Условия использования</small></a>   <a class="text-muted pl-10" href="/privacy/"><small>Конфиденциальность</small></a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
{% load staticfiles %}
{% load main_menu %}
<div class="header-container">
    <div class="header-top dark ">
        <div class="container">
            <div class="row">
                <div class="col-xs-2 col-sm-3">
                    <div class="header-top-first clearfix">
                        <ul class="social-links circle small clearfix hidden-xs">
                            <li class="facebook"><a rel="nofollow" target="_blank" href="https://www.facebook.com/sunSailing.com.ua"><i class="fa fa-facebook"></i></a></li>
                            <li class="youtube"><a rel="nofollow" target="_blank" href="https://www.youtube.com/user/sunSailingYachts"><i class="fa fa-youtube"></i></a></li>
                            <li class="instagram"><a rel="nofollow" target="_blank" href="https://instagram.com/sunsailingua/"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                        <div class="social-links hidden-lg hidden-md hidden-sm circle small">
                            <div class="btn-group dropdown">
                                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-share-alt"></i></button>
                                <ul class="dropdown-menu dropdown-animation">
                                    <li class="facebook"><a rel="nofollow" target="_blank" href="https://www.facebook.com/sunSailing.com.ua"><i class="fa fa-facebook"></i></a></li>
                                    <li class="youtube"><a rel="nofollow" target="_blank" href="https://www.youtube.com/user/sunSailingYachts"><i class="fa fa-youtube"></i></a></li>
                                    <li class="instagram"><a target="_blank" href="https://instagram.com/sunsailingua/"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-10 col-sm-9">
                    <div id="header-top-second"  class="clearfix text-right">
                        <ul class="list-inline">
                            <li><a href="skype:sunsailingua?add" class="link-light" title="Добавить sunsailingua в список контактов Skype"><i class="fa fa-skype pr-5 pl-10"></i> <span class="hidden-xs hidden-sm">sunsailingua</span></a></li>
                            <li><a href="mailto:office@sunsailing.com.ua" class="link-light"><i class="fa fa-envelope-o pr-5 pl-10"></i> <span class="hidden-xs hidden-sm">office@sunsailing.com.ua</span></a></li>
                            <li class="hidden-xs"><i class="fa fa-phone pr-5 pl-10"></i>+380 (44) 383-31-57</li>
                            <li><i class="fa fa-mobile pr-5 pl-10"></i>+380 (67) 226-83-96</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <header class="header  fixed   clearfix">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="header-left clearfix">
                        <div id="logo" class="logo">
                            <a href="{% url 'home' %}"><img id="logo_img" src="{% static "base/images/logo.png" %}" alt="sunSailing"></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="header-right clearfix">
                    <div class="main-navigation  animated with-dropdown-buttons">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                                        <span class="sr-only">Переключатель навигации</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <div class="calc-tour">
                                        <a rel="nofollow" href="{% url 'feedbackform:tour_calculation' %}" class="btn btn-sm visible-xs btn-default" >Рассчитать тур на яхте <i class="fa fa-calculator pl-5"></i></a>
                                    </div>
                                </div>
                                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                                    <ul class="nav navbar-nav ">
                                        {% main_menu_show request.path 41 as main_menu %}
                                        {{ main_menu|safe }}
                                    </ul>
                                    <div class="header-dropdown-buttons">
                                        <a rel="nofollow" href="{% url 'feedbackform:tour_calculation' %}" class="btn btn-sm hidden-xs btn-default">Рассчитать тур <i class="fa fa-calculator pl-5"></i></a>
                                    </div>
                                </div>
                            </div>
                        </nav>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
</div>

templates/socialshare.html
<ul class="social-links circle small colored clearfix margin-clear text-right animated-effect-1">
    <li class="facebook"><a rel="nofollow" title="Поделиться в Facebook" target="_blank" href="http://www.facebook.com/sharer.php?u={{ request.build_absolute_uri }}"><i class="fa fa-facebook"></i></a></li>
    <li class="googleplus"><a rel="nofollow" title="Поделиться в GooglePlus" target="_blank" href="http://plus.google.com/share?url={{ request.build_absolute_uri }}"><i class="fa fa-google-plus"></i></a></li>
    <li class="twitter"><a rel="nofollow" title="Поделиться в Twitter" target="_blank" href="http://www.twitter.com/share?url={{ request.build_absolute_uri }}"><i class="fa fa-twitter"></i></a></li>
    <li class="vk"><a rel="nofollow" title="Поделиться в Вконтакте" target="_blank" href="http://vkontakte.ru/share.php?url={{ request.build_absolute_uri }}"><i class="fa fa-vk"></i></a></li>
</ul>