school/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^kruizy-s-obucheniem/$', CruiseList.as_view(), name = 'cruise_list'),
    url(r'^kruizy-s-obucheniem/(?P<slug>[\w-]+)/$', CruiseDetail.as_view(), name = 'cruise_detail'),
    url(r'^(?P<slug>[\w-]+)/$', TheoryView.as_view(), name = 'theory_detail'),
    ]

school/models.py
import os

from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.core.urlresolvers import reverse
from django.utils import dateformat
from django.conf import settings

from utils import img_utils


class Theory(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    sidebar_title = models.CharField(max_length=255)
    text = models.TextField()
    order_id = models.IntegerField(blank = True, null = True)
    photo_single = GenericRelation('photobank.SinglePhoto')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('school:theory_detail', args=[self.slug])

    class Meta:
        ordering = ('order_id',)


class TheoryStart(models.Model):
    start_date = models.DateField()

    def __str__(self):
        return dateformat.format(self.start_date, 'j F Y')

    class Meta:
        ordering = ('start_date',)


class Cruise(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique = True)
    subtitle = models.CharField(max_length=255, null=True)
    banner_image = models.ImageField(upload_to='school/cruise/banner_image/')
    card_image = models.ImageField(upload_to='school/cruise/card_image/', help_text='Auto resize to 740px')

    start_port = models.CharField(max_length=255)

    cruise_description = models.TextField()
    cruise_program = models.TextField()
    afterword = models.TextField(null=True, blank=True)

    yacht = models.ForeignKey('yachtcharter.Yacht', null=True)
    cabin = models.CharField(max_length=255, null=True)
    wc = models.CharField(max_length=255, null=True)

    price_description = models.TextField(null=True, blank=True)

    order_id = models.PositiveIntegerField(blank=True, null=True)

    photo_single = GenericRelation('photobank.SinglePhoto')

    def save(self, *args, **kwargs):
        if not os.path.isfile(self.card_image.path):
            self.card_image = img_utils.resize_ratio(740, self.card_image.file)
        super(Cruise, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('school:cruise_detail', args=[self.slug])

    class Meta:
        ordering = ('order_id',)


class Price(models.Model):
    cruise = models.ForeignKey(Cruise)
    date_from = models.DateField()
    date_to = models.DateField()
    price = models.PositiveIntegerField()

    class Meta:
        ordering = ('date_from',)


class PriceInclude(models.Model):
    offer = models.ForeignKey(Cruise)
    include = models.CharField(max_length=255)
    order_id = models.PositiveIntegerField( blank = True, null = True)

    class Meta:
        ordering = ('order_id',)


class PriceExclude(models.Model):
    offer = models.ForeignKey(Cruise)
    exclude = models.CharField(max_length=255)
    order_id = models.PositiveIntegerField( blank = True, null = True)

    class Meta:
        ordering = ('order_id',)

school/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView

from .models import Theory, TheoryStart, Cruise


class TheoryView(TemplateView):
    template_name = 'school/theory_detail.html'

    def get_context_data(self, **kwargs):
        context = super(TheoryView, self).get_context_data(**kwargs)
        context['theory'] = get_object_or_404(Theory, slug=kwargs['slug'])
        context['theory_start'] = TheoryStart.objects.all()
        context['theory_list'] = Theory.objects.all()
        return context


class CruiseList(ListView):
    queryset = Cruise.objects.prefetch_related('price_set').all()
    context_object_name = 'cruise_list'
    template_name = "school/cruise_list.html"


class CruiseDetail(DetailView):
    model = Cruise
    context_object_name = 'cruise'
    template_name = "school/cruise_detail.html"

school/templates/school/cruise_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load banner %}
{% load seo %}

{% block meta-og %}
    <meta property="og:type" content="product" />
    <meta property="og:site_name" content="{% site_name %}" >
    <meta property="fb:app_id" content="{% fb_id %}" />
    <meta property="og:title" content="{{ cruise.title  }} - {{ cruise.subtitle }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="http://{{ request.get_host }}{{ cruise.card_image.url }}" />
{% endblock %}

{% block extra-css %}
    <link href="{% static 'bootstraptemplate/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
{% endblock %}
{% block extra-js %}
    <script type="text/javascript" src="{% static 'bootstraptemplate/plugins/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
{% endblock %}


{% block banner-image %}{{ cruise.banner_image.url }}{% endblock %}
{% block banner-breadcrumbs %}{% breadcrumbs_show 'school:cruise_list' cruise.get_absolute_url cruise.title %}{% endblock %}
{% block banner-title %}{{ cruise.title }}{% endblock %}
{% block banner-subtitle %}{{ cruise.subtitle }}{% endblock %}


{% block main-container %}
    {% load humanize %}
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="main col-md-12">
                    <div class="blogpost">
                        {{ cruise.cruise_description|safe }}
                    </div>
                    <div class="blogpost">
                        <h2>Круиз на {{ cruise.yacht.yacht_type.title_prepositional|lower }} <strong>{{ cruise.yacht.title }}</strong></h2>
                        <div class="separator-2"></div>
                        <div class="row space-bottom">
                            <div class="col-md-6">
                                {% for img in cruise.yacht.get_obj_by_type.photo_gallery.charter_images.all %}
                                    {% if forloop.first %}
                                        <div class="shadow bordered">
                                            <div class="overlay-container">
                                                <img src="{{ img.image.url }}" alt="{{ cruise.yacht.title }},  {{ cruise.yacht.cabin_display }} кают(ы){% if cruise.yacht.built_year %}, {{ cruise.yacht.built_year }} г. выпуска {% endif %}">
                                                <a href="{{ img.image.url }}" class="overlay-link popup-img">
                                                    <i class="fa fa-plus"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="space-bottom"></div>
                                    {% endif %}
                                    {% if forloop.first %}
                                        <div class="row grid-space-20">
                                    {% endif %}
                                    {% if not forloop.first %}
                                            <div class="col-xs-4">
                                                <div class="overlay-container">
                                                    <img src="{{ img.thumbnail.url }}" alt="{{ cruise.yacht.title }},  {{ cruise.yacht.cabin_display }} кают(ы){% if cruise.yacht.built_year %}, {{ cruise.yacht.built_year }} г. выпуска {% endif %}">
                                                    <a href="{{ img.image.url }}" class="overlay-link small popup-img">
                                                        <i class="fa fa-plus"></i>
                                                    </a>
                                                </div>
                                            </div>
                                    {% endif %}
                                    {% if forloop.last %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                                <div class="space-bottom"></div>
                            </div>
                            <div class="col-md-6">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th colspan="2">Характеристики {{ cruise.yacht.yacht_type.title_genitive|lower }}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Бренд</td>
                                            <td class="information">
                                                {{ cruise.yacht.get_obj_by_type.shipyard.title }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Длина</td>
                                            <td class="information">
                                                {{ cruise.yacht.length }} м = {{ cruise.yacht.length_ft }} фт
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Ширина</td>
                                            <td class="information">
                                                {{ cruise.yacht.beam }} м = {{ cruise.yacht.beam_ft }} фт
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Осадка</td>
                                            <td class="information">
                                                {{ cruise.yacht.get_obj_by_type.draft }} м = {{ cruise.yacht.get_obj_by_type.draft_ft }} фт
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Кают</td>
                                            <td class="information">
                                                {{ cruise.cabin }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>WC</td>
                                            <td class="information">
                                                {{ cruise.wc }}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <a href="{{ cruise.yacht.get_absolute_url }}" class="btn btn-animated btn-default-transparent btn-sm">Подробнее <i class="fa fa-arrow-right"></i></a>
                            </div>
                        </div>
                        {{ cruise.price_description|safe }}
                        <div class="table-responsive listing-item">
                            <table class="table table-price table-hover">
                            <tbody>
                            {% for price in cruise.price_set.all %}
                                <tr>
                                    <td>{{ price.date_from }} &mdash; {{ price.date_to }}</td>
                                    <td class="text-center"><span class="price">{{ price.price|intcomma }} €</span></td>
                                    <td><a rel="nofollow" href="{% url 'feedbackform:school_cruise' price.id %}" class="pull-right margin-clear btn btn-sm btn-default btn-animated">Забронировать место<i class="fa fa-arrow-right"></i></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <h3>В стоимость включено</h3>
                                <ul class="list-icons">
                                    {% for item in cruise.priceinclude_set.all %}
                                        <li><i class="icon-check"></i> {{ item.include|safe }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <h3>Дополнительно оплачивается</h3>
                                <ul class="list-icons">
                                    {% for item in cruise.priceexclude_set.all %}
                                        <li><i class="icon-plus float-left"></i> {{ item.exclude|safe }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="blogpost">
                        <h2>Программа круиза</h2>
                        <div class="separator-2"></div>
                        <div class="alert alert-info" >
                            <p>Место старта &mdash; <strong>{{ cruise.start_port }}</strong></p>
                        </div>
                        <div class="space-bottom"></div>
                        {{ cruise.cruise_program|safe }}
                    </div>
                    {% if cruise.afterword|length > 0  %}
                        <div class="blogpost">
                            {{ cruise.afterword|safe }}
                        </div>
                    {% endif %}
                    <div class="blogpost">
                        <p class="lead"><strong>До встречи на яхте!</strong></p>
                    </div>
                    <div class="blogpost full">
                        <footer class="clearfix">
                            <div class="link pull-left">
                                {% include "socialshare.html" %}
                            </div>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

school/templates/school/cruise_list.html
{% extends "base.html" %}
{% load banner %}


{% block banner-image %}{% menu_banner_image 'school:cruise_list' %}{% endblock %}
{% block banner-breadcrumbs %}{% breadcrumbs_show 'school:cruise_list' %}{% endblock %}
{% block banner-title %}{% menu_banner_title 'school:cruise_list' %}{% endblock %}
{% block banner-subtitle %}{% menu_banner_subtitle 'school:cruise_list' %}{% endblock %}


{% block main-container %}
    {% load humanize %}
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="main col-md-12">
                    <div class="row">
                        {% for cruise in cruise_list %}
                            <div class="col-md-4">
                                <div class="listing-item white-bg bordered mb-20">
                                    <div class="overlay-container">
                                        <img src="{{ cruise.card_image.url }}" alt="{{ cruise.title }}">
                                        <a href="{{ cruise.get_absolute_url }}" class="overlay-link"><i class="fa fa-anchor"></i> </a>
                                        <span class="badge">{{ cruise.period }}</span>
                                    </div>
                                    <div class="body">
                                        <h3><a href="{{ cruise.get_absolute_url }}">{{ cruise.title }}</a></h3>
                                        <div class="separator-2"></div>
                                        {% for row in cruise.price_set.all %}
                                            <div class="row">
                                            <div class="col-md-9">
                                                {{ row.date_from|date:'j N Y' }} &mdash; {{ row.date_to|date:'j N Y'}}
                                            </div>
                                            <div class="col-md-3">
                                                <span class="price">{{ row.price|intcomma }} €</span>
                                            </div>
                                            </div>
                                        {% endfor %}
                                        Место старта: {{ cruise.start_port }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

school/templates/school/theory_detail.html
{% extends "base.html" %}
{% load banner %}

{% block banner-image %}{% menu_banner_image theory.get_absolute_url True %}{% endblock %}
{% block banner-breadcrumbs %}{% breadcrumbs_show theory.get_absolute_url abs_url=True %}{% endblock %}
{% block banner-title %}{% menu_banner_title theory.get_absolute_url True %}{% endblock %}
{% block banner-subtitle %}{% menu_banner_subtitle theory.get_absolute_url True %}{% endblock %}


{% block main-container %}
    <section class="main-container">
        <div class="container">
            <div class="row">
                <div class="main col-md-8">
                        <div class="blogpost">
                            {{ theory.text|safe }}
                        </div>
                        <div class="blogpost">
                            <div class="call-to-action well">
                                <h2 class="title">Хотите научится управлять яхтой?</h2>
                                <p>Записывайтесь на теоретический курс прямой сейчас!</p>
                                <div class="table-responsive">
                                <table class="table table-price">
                                    <tr>
                                        <td>Начало занятий:</td>
                                        <td>
                                            {% for start_date in theory_start %}
                                                {{ start_date.start_date }}
                                                {% if not forloop.last %}
                                                    <br>
                                                {% endif %}
                                            {% endfor %}
                                        </td>
                                    </tr>
                                    <tr >
                                        <td>Группы:</td>
                                        <td>вечерние: 19:00 - 21:30<br>выходного дня: 10:00 - 14:00</td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">Дистанционный курс - в любое время</td>
                                    </tr>
                                </table>
                                </div>
                                <a rel="nofollow" href="{% url 'feedbackform:school_theory' %}" class="btn btn-lg btn-default btn-animated">Записаться на курс<i class="fa fa-arrow-right pl-20"></i></a>
                            </div>
                        </div>
                </div>
                <div class="col-md-4 col-lg-3 col-lg-offset-1">
                    <div class="sidebar">
                        <h3 class="title">Школа яхтинга</h3>
                        <div class="separator-2"></div>
                        <nav class="affix-menu scrollspy">
                            <ul class="smooth-scroll nav nav-pills nav-stacked">
                                {% for section in theory_list %}
                                    <li {% if section.slug == theory.slug %} class="active"{% endif %}><a href="{{ section.get_absolute_url }}">{{ section.sidebar_title }}</a></li>
                                {% endfor %}
                                <li><a href="{% url 'school:cruise_list' %}">Практические круизы</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}